### ISSUE TITLE
Current version of Guzzle library do not work with PHP 7

### ISSUE THREAD

**Issue by steinmb** [nt2-labo/cell_migrate_oaipmh#14]
The composer file currently used define a too old version. Running it in test and 7.x. give. Related to issue #12 

```
drush -l cellproject.local ms
PHP Fatal error:  Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313

Fatal error: Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313
```

## Suggested fix

Upgrade to newer version, it was fixed [back in 2015](https://github.com/guzzle/guzzle/issues/1015)
By updating `migrate_oaipmh` it also push libraries to the newer versions that work with a modern PHP 7.0 and newer versions.

**Comment by steinmb** [comment]
Adding adding a full stack trace:

```
HP Stack trace:
PHP   1. {main}() /Users/steinmb/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /Users/steinmb/.composer/vendor/drush/drush/drush.php:12
PHP   3. Drush\Boot\DrupalBoot7->bootstrap_and_dispatch() /Users/steinmb/.composer/vendor/drush/drush/includes/preflight.inc:66
PHP   4. drush_dispatch() /Users/steinmb/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
PHP   5. drush_command() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:199
PHP   6. _drush_invoke_hooks() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:231
PHP   7. drush_migrate_status() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:422
PHP   8. migrate_migrations() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.drush.inc:314
PHP   9. MigrationBase::getInstance() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.module:76
PHP  10. CellNodeMigration->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/includes/base.inc:647
PHP  11. CellMigrateSourceOaiPmh->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/custom/cell_migrate_oaipmh/includes/migration.inc:148
PHP  12. Phpoaipmh\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate_oaipmh/includes/oaipmh.inc:65
PHP  13. Phpoaipmh\HttpAdapter\GuzzleAdapter->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/Client.php:62
PHP  14. GuzzleHttp\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/HttpAdapter/GuzzleAdapter.php:31
PHP  15. GuzzleHttp\Client::getDefaultHandler() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:92
PHP  16. spl_autoload_call() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
PHP  17. Composer\Autoload\ClassLoader->loadClass() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
PHP  18. Composer\Autoload\includeFile() /Users/steinmb/.composer/vendor/composer/ClassLoader.php:322

Fatal error: Redefinition of parameter $_ in /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313

Call Stack:
    0.0019     354272   1. {main}() /Users/steinmb/.composer/vendor/drush/drush/drush.php:0
    0.0034     500424   2. drush_main() /Users/steinmb/.composer/vendor/drush/drush/drush.php:12
    0.2583    8876272   3. Drush\Boot\DrupalBoot7->bootstrap_and_dispatch() /Users/steinmb/.composer/vendor/drush/drush/includes/preflight.inc:66
    0.9718   35805504   4. drush_dispatch() /Users/steinmb/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
    1.0953   37536840   5. drush_command() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:199
    1.0955   37536936   6. _drush_invoke_hooks() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:231
    1.1041   37782704   7. drush_migrate_status() /Users/steinmb/.composer/vendor/drush/drush/includes/command.inc:422
    1.1043   37783048   8. migrate_migrations() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.drush.inc:314
    1.1376   38462024   9. MigrationBase::getInstance() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/migrate.module:76
    1.1442   38477064  10. CellNodeMigration->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate/includes/base.inc:647
    1.1469   38502344  11. CellMigrateSourceOaiPmh->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/custom/cell_migrate_oaipmh/includes/migration.inc:148
    1.1480   38516248  12. Phpoaipmh\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/modules/ajout-nt2/migrate_oaipmh/includes/oaipmh.inc:65
    1.1531   38656704  13. Phpoaipmh\HttpAdapter\GuzzleAdapter->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/Client.php:62
    1.1531   38656832  14. GuzzleHttp\Client->__construct() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/caseyamcl/phpoaipmh/src/Phpoaipmh/HttpAdapter/GuzzleAdapter.php:31
    1.1600   38813768  15. GuzzleHttp\Client::getDefaultHandler() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:92
    1.1645   38948968  16. spl_autoload_call() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
    1.1645   38949032  17. Composer\Autoload\ClassLoader->loadClass() /Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/guzzle/src/Client.php:121
    1.1646   38949224  18. Composer\Autoload\includeFile() /Users/steinmb/.composer/vendor/composer/ClassLoader.php:322

Drush command terminated abnormally due to an unrecoverable error.                                                                                                        [error]
Error: Redefinition of parameter $_ in
/Users/steinmb/sites/cellproject/cellproject/sites/cellproject.net/libraries/composer/guzzlehttp/ringphp/src/Client/StreamHandler.php, line 313
```

**Comment by steinmb** [comment]
Updating Update migrate_oaipmh.

commit 756e2b210252a68967becc888f135e8064c64617
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Aug 28 18:51:26 2018 +0100

    Update migrate_oaipmh and libraries to latest version

    This push Guzzle and depending lib. to a version
    that work with modern PHP 7.0 and newer.

This introduce a newer generation and version that work with PHP 7.x. There is stuff in the log that do not work though that might be totally unrelated to this issue:

### Test migrate status

`drush -l cellproject.local ms`

```
Server error: `GET                                                                                                                                                        [error]
https://adel.uni-siegen.de/cell-oai-pmh?verb=ListRecords&resumptionToken%5Bidentifier%5D=header%2Fidentifier&resumptionToken%5Bmods%2FrecordInfo%2FrecordContentSource%5D=mods%2FrecordInfo%2FrecordContentSource&resumptionToken%5Bmods%2FtitleInfo%2Ftitle%5D=mods%2FtitleInfo%2Ftitle&resumptionToken%5Bmods%2ForiginInfo%2FdateIssued%5D=mods%2ForiginInfo%2FdateIssued&resumptionToken%5Bmods%2Flanguage%2FlanguageTerm%5D=mods%2Flanguage%2FlanguageTerm&resumptionToken%5Bmods%2Flocation%2Furl%5D=mods%2Flocation%2Furl&resumptionToken%5Bmods%2Fidentifier%5D=mods%2Fidentifier&resumptionToken%5Bmods%2Fextension%2FrecordInfo%2Fname%2FnamePart%5D=mods%2Fextension%2FrecordInfo%2Fname%2FnamePart&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Ftechnology%5D=mods%2FphysicalDescription%2Fform%2Ftechnology&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type-complementary%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28without+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality%5D=mods%2Fgenre%2Fprocedural-modality+%28with+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality-complementary%5D=mods%2Fgenre%2Fprocedural-modality+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism-complementary%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat-complementary%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28without+authority%29&resumptionToken%5Bmods%2Fabstract%5D=mods%2Fabstract&resumptionToken%5Bmods%2Fgenre%2Fliterary-quality%5D=mods%2Fgenre%2Fliterary-quality&resumptionToken%5Bmods%2FrecordInfo%2FrecordCreationDate%5D=mods%2FrecordInfo%2FrecordCreationDate&resumptionToken%5Bmods%2FrecordInfo%2FrecordChangeDate%5D=mods%2FrecordInfo%2FrecordChangeDate&resumptionToken%5Bmods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm%5D=mods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm`
resulted in a `500 Service unavailable (with message)` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xm (truncated...)

The request includes illegal arguments, is missing required arguments, includes a repeated argument, or values for arguments have an illegal syntax.                      [error]
The required argument 'metadataPrefix' is missing.                                                                                                                        [error]
Server error: `GET                                                                                                                                                        [error]
http://elmcip.net/data/work/oai-pmh?verb=ListRecords&resumptionToken%5Bidentifier%5D=header%2Fidentifier&resumptionToken%5Bmods%2FrecordInfo%2FrecordContentSource%5D=mods%2FrecordInfo%2FrecordContentSource&resumptionToken%5Bmods%2FtitleInfo%2Ftitle%5D=mods%2FtitleInfo%2Ftitle&resumptionToken%5Bmods%2ForiginInfo%2FdateIssued%5D=mods%2ForiginInfo%2FdateIssued&resumptionToken%5Bmods%2Flanguage%2FlanguageTerm%5D=mods%2Flanguage%2FlanguageTerm&resumptionToken%5Bmods%2Flocation%2Furl%5D=mods%2Flocation%2Furl&resumptionToken%5Bmods%2Fidentifier%5D=mods%2Fidentifier&resumptionToken%5Bmods%2Fextension%2FrecordInfo%2Fname%2FnamePart%5D=mods%2Fextension%2FrecordInfo%2Fname%2FnamePart&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Ftechnology%5D=mods%2FphysicalDescription%2Fform%2Ftechnology&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type-complementary%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28without+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality%5D=mods%2Fgenre%2Fprocedural-modality+%28with+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality-complementary%5D=mods%2Fgenre%2Fprocedural-modality+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism-complementary%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat-complementary%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28without+authority%29&resumptionToken%5Bmods%2Fabstract%5D=mods%2Fabstract&resumptionToken%5Bmods%2Fgenre%2Fliterary-quality%5D=mods%2Fgenre%2Fliterary-quality&resumptionToken%5Bmods%2FrecordInfo%2FrecordCreationDate%5D=mods%2FrecordInfo%2FrecordCreationDate&resumptionToken%5Bmods%2FrecordInfo%2FrecordChangeDate%5D=mods%2FrecordInfo%2FrecordChangeDate&resumptionToken%5Bmods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm%5D=mods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm`
resulted in a `500 Service unavailable (with message)` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xm (truncated...)

Server error: `GET                                                                                                                                                        [error]
http://nt2.uqam.ca/en/oai-pmh?verb=ListRecords&resumptionToken%5Bidentifier%5D=header%2Fidentifier&resumptionToken%5Bmods%2FrecordInfo%2FrecordContentSource%5D=mods%2FrecordInfo%2FrecordContentSource&resumptionToken%5Bmods%2FtitleInfo%2Ftitle%5D=mods%2FtitleInfo%2Ftitle&resumptionToken%5Bmods%2ForiginInfo%2FdateIssued%5D=mods%2ForiginInfo%2FdateIssued&resumptionToken%5Bmods%2Flanguage%2FlanguageTerm%5D=mods%2Flanguage%2FlanguageTerm&resumptionToken%5Bmods%2Flocation%2Furl%5D=mods%2Flocation%2Furl&resumptionToken%5Bmods%2Fidentifier%5D=mods%2Fidentifier&resumptionToken%5Bmods%2Fextension%2FrecordInfo%2Fname%2FnamePart%5D=mods%2Fextension%2FrecordInfo%2Fname%2FnamePart&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Ftechnology%5D=mods%2FphysicalDescription%2Fform%2Ftechnology&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fpublication-type-complementary%5D=mods%2FphysicalDescription%2Fform%2Fpublication-type+%28without+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality%5D=mods%2Fgenre%2Fprocedural-modality+%28with+authority%29&resumptionToken%5Bmods%2Fgenre%2Fprocedural-modality-complementary%5D=mods%2Fgenre%2Fprocedural-modality+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fmechanism-complementary%5D=mods%2FphysicalDescription%2Fform%2Fmechanism+%28without+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28with+authority%29&resumptionToken%5Bmods%2FphysicalDescription%2Fform%2Fformat-complementary%5D=mods%2FphysicalDescription%2Fform%2Fformat+%28without+authority%29&resumptionToken%5Bmods%2Fabstract%5D=mods%2Fabstract&resumptionToken%5Bmods%2Fgenre%2Fliterary-quality%5D=mods%2Fgenre%2Fliterary-quality&resumptionToken%5Bmods%2FrecordInfo%2FrecordCreationDate%5D=mods%2FrecordInfo%2FrecordCreationDate&resumptionToken%5Bmods%2FrecordInfo%2FrecordChangeDate%5D=mods%2FrecordInfo%2FrecordChangeDate&resumptionToken%5Bmods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm%5D=mods%2FrecordInfo%2FlanguageOfCataloging%2FlanguageTerm`
resulted in a `500 Service unavailable (with message)` response:
<!DOCTYPE html>
<!--[if IEMobile 7]><html class="iem7"  lang="en" dir="ltr"><![endif]-->
<!--[if lte IE 6]><html class=" (truncated...)

cURL error 6: Could not resolve host: beta.po-ex.net (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                                                              [error]

 Group: ADEL            Total  Imported  Unprocessed  Status  Last imported
 ADELCellNode           N/A    799       -799         Idle    2018-05-29 10:41:13

 Group: Ciberia         Total  Imported  Unprocessed  Status  Last imported
 CiberiaCellNode        N/A    54        -58          Idle    2018-05-04 10:17:52

 Group: ELD             Total  Imported  Unprocessed  Status  Last imported
 ELDCellNode            N/A    483       -483         Idle    2018-05-04 09:04:48

 Group: ELMCIP          Total  Imported  Unprocessed  Status  Last imported
 ELMCIPCellNode         N/A    3031      -3031        Idle    2018-08-28 13:32:43

 Group: NT2CELLOAIPMH   Total  Imported  Unprocessed  Status  Last imported
 NT2CELLOAIPMHCellNode  N/A    180       -180         Idle    2018-05-04 08:49:46

 Group: POEX            Total  Imported  Unprocessed  Status  Last imported
 POEXCellNode           N/A    5         -5           Idle    2018-05-04 08:52:23
```

**Comment by steinmb** [comment]
Mental note. Some digging around and traced it back to where  `sites/cellproject.net/modules/ajout-nt2/migrate_oaipmh/includes/oaipmh.inc` query the end point `listRecords`.

      // Get a ResponseList object to fetch the source records.
    $this->sourceRecords = $this->endpoint->listRecords($this->metadataPrefix, $this->from, $this->until, $this->set, $this->resumptionToken);

To

    $this->sourceRecords = $this->endpoint->listRecords($this->metadataPrefix);

The errors go away meaning, some of the parameters passed in is prob. wrong. Prob. the iterator interface bit using resumptionToken.

```
Array
(
    [identifier] => header/identifier
    [mods/recordInfo/recordContentSource] => mods/recordInfo/recordContentSource
    [mods/titleInfo/title] => mods/titleInfo/title
    [mods/originInfo/dateIssued] => mods/originInfo/dateIssued
    [mods/language/languageTerm] => mods/language/languageTerm
    [mods/location/url] => mods/location/url
    [mods/identifier] => mods/identifier
    [mods/extension/recordInfo/name/namePart] => mods/extension/recordInfo/name/namePart
    [mods/physicalDescription/form/technology] => mods/physicalDescription/form/technology
    [mods/physicalDescription/form/publication-type] => mods/physicalDescription/form/publication-type (with authority)
    [mods/physicalDescription/form/publication-type-complementary] => mods/physicalDescription/form/publication-type (without authority)
    [mods/genre/procedural-modality] => mods/genre/procedural-modality (with authority)
    [mods/genre/procedural-modality-complementary] => mods/genre/procedural-modality (without authority)
    [mods/physicalDescription/form/mechanism] => mods/physicalDescription/form/mechanism (with authority)
    [mods/physicalDescription/form/mechanism-complementary] => mods/physicalDescription/form/mechanism (without authority)
    [mods/physicalDescription/form/format] => mods/physicalDescription/form/format (with authority)
    [mods/physicalDescription/form/format-complementary] => mods/physicalDescription/form/format (without authority)
    [mods/abstract] => mods/abstract
    [mods/genre/literary-quality] => mods/genre/literary-quality
    [mods/recordInfo/recordCreationDate] => mods/recordInfo/recordCreationDate
    [mods/recordInfo/recordChangeDate] => mods/recordInfo/recordChangeDate
    [mods/recordInfo/languageOfCataloging/languageTerm] => mods/recordInfo/languageOfCataloging/languageTerm
)
```

**Comment by steinmb** [comment]
```

Array
(
    [identifier] => header/identifier
    [mods/recordInfo/recordContentSource] => mods/recordInfo/recordContentSource
    [mods/titleInfo/title] => mods/titleInfo/title
    [mods/originInfo/dateIssued] => mods/originInfo/dateIssued
    [mods/language/languageTerm] => mods/language/languageTerm
    [mods/location/url] => mods/location/url
    [mods/identifier] => mods/identifier
    [mods/extension/recordInfo/name/namePart] => mods/extension/recordInfo/name/namePart
    [mods/physicalDescription/form/technology] => mods/physicalDescription/form/technology
    [mods/physicalDescription/form/publication-type] => mods/physicalDescription/form/publication-type (with authority)
    [mods/physicalDescription/form/publication-type-complementary] => mods/physicalDescription/form/publication-type (without authority)
    [mods/genre/procedural-modality] => mods/genre/procedural-modality (with authority)
    [mods/genre/procedural-modality-complementary] => mods/genre/procedural-modality (without authority)
    [mods/physicalDescription/form/mechanism] => mods/physicalDescription/form/mechanism (with authority)
    [mods/physicalDescription/form/mechanism-complementary] => mods/physicalDescription/form/mechanism (without authority)
    [mods/physicalDescription/form/format] => mods/physicalDescription/form/format (with authority)
    [mods/physicalDescription/form/format-complementary] => mods/physicalDescription/form/format (without authority)
    [mods/abstract] => mods/abstract
    [mods/genre/literary-quality] => mods/genre/literary-quality
    [mods/recordInfo/recordCreationDate] => mods/recordInfo/recordCreationDate
    [mods/recordInfo/recordChangeDate] => mods/recordInfo/recordChangeDate
    [mods/recordInfo/languageOfCataloging/languageTerm] => mods/recordInfo/languageOfCataloging/languageTerm
)

Array
(
    [identifier] => header/identifier
    [mods/recordInfo/recordContentSource] => mods/recordInfo/recordContentSource
    [mods/titleInfo/title] => mods/titleInfo/title
    [mods/originInfo/dateIssued] => mods/originInfo/dateIssued
    [mods/language/languageTerm] => mods/language/languageTerm
    [mods/location/url] => mods/location/url
    [mods/identifier] => mods/identifier
    [mods/extension/recordInfo/name/namePart] => mods/extension/recordInfo/name/namePart
    [mods/physicalDescription/form/technology] => mods/physicalDescription/form/technology
    [mods/physicalDescription/form/publication-type] => mods/physicalDescription/form/publication-type (with authority)
    [mods/physicalDescription/form/publication-type-complementary] => mods/physicalDescription/form/publication-type (without authority)
    [mods/genre/procedural-modality] => mods/genre/procedural-modality (with authority)
    [mods/genre/procedural-modality-complementary] => mods/genre/procedural-modality (without authority)
    [mods/physicalDescription/form/mechanism] => mods/physicalDescription/form/mechanism (with authority)
    [mods/physicalDescription/form/mechanism-complementary] => mods/physicalDescription/form/mechanism (without authority)
    [mods/physicalDescription/form/format] => mods/physicalDescription/form/format (with authority)
    [mods/physicalDescription/form/format-complementary] => mods/physicalDescription/form/format (without authority)
    [mods/abstract] => mods/abstract
    [mods/genre/literary-quality] => mods/genre/literary-quality
    [mods/recordInfo/recordCreationDate] => mods/recordInfo/recordCreationDate
    [mods/recordInfo/recordChangeDate] => mods/recordInfo/recordChangeDate
    [mods/recordInfo/languageOfCataloging/languageTerm] => mods/recordInfo/languageOfCataloging/languageTerm
)

```
